# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MAIN WEBSITE TITLE
email: darude@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: /nard # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#The default Jekyll theme:
theme: minima  
#Find more themes here: https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme
#theme: CUSTOM #Custom imported theme


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


#USER ADDED:
#Make sure to restart the Jekyll server whenver you modify the _config.yml file.
defaults:
  -
    #The default matter will override all files in the directory it is specified to, unless a specific type is used in scope.
    scope:
      path: "_posts/New-Dir-Posts"            #Select which files to apply the default values. 
      #path: ""                               #Leave as blank and it will apply to all.
      type: "posts"                           #The type of files we want to affect, incase there are other file types in the directory.
    values:
      layout: "post"
      title: "DEFAULT TITLE"
      date:   2010-01-01 01:00:00 0000

    scope:
      path: "assets/images"
    values:
      image: true                             #State that the files here are in fact images.

#ALSO EDITTED THEME SETTINGS.
      #Theme edits are also done in Gemfile by adding the attribute:gem "github-pages", group: :jekyll_plugins