title: Your awesome title
email: your-email@example.com

baseurl: /beta # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    #The default matter will override all files in the directory it is specified to, unless a specific type is used in scope.
    scope:
      path: "{{site.baseurl}}_posts/New-Dir-Posts"            #Select which files to apply the default values. 
      #path: ""                               #Leave as blank and it will apply to all.
      type: "posts"                           #The type of files we want to affect, incase there are other file types in the directory.
    values:
      layout: "post"
      title: "DEFAULT TITLE"
      date:   2010-01-01 01:00:00 0000

    scope:
      path: "{{site.baseurl}}assets/images"
    values:
      image: true  
