title: MAIN WEBSITE TITLE
email: darude@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: '/Beta-Site/'
url: https://senorlok.github.io

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#The default Jekyll theme:
theme: minima  
#Find more themes here: https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme
#theme: CUSTOM #Custom imported theme


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


#USER ADDED:
#Make sure to restart the Jekyll server whenver you modify the _config.yml file.
defaults:
  -
    #The default matter will override all files in the directory it is specified to, unless a specific type is used in scope.
    scope:
      path: "_posts/New-Dir-Posts"            #Select which files to apply the default values. 
      #path: ""                               #Leave as blank and it will apply to all.
      type: "posts"                           #The type of files we want to affect, incase there are other file types in the directory.
    values:
      layout: "post"
      title: "DEFAULT TITLE"
      date:   2010-01-01 01:00:00 0000

    scope:
      path: "assets/images"
    values:
      image: true                             #State that the files here are in fact images.

#ALSO EDITTED THEME SETTINGS.
      #Theme edits are also done in Gemfile by adding the attribute:gem "github-pages", group: :jekyll_plugins
